---
title: "template"
subtitle: "template"
author: "bob"
output:
  html_document:
    code_download: true # embed .Rmd file
    toc: true  # table of contents
    toc_depth: 3
    toc_float: true # toc is always visible when scrolled
    number_sections: true 
    theme: sandstone # theme the doc
    highlight: tango # theme syntax colouring
---

```{css newstyles, echo=FALSE}
h1, .h1, h2, .h2, h3, .h3 { /* Add space before headings: */
    margin-top: 56px;
}
h1, h2 { /* add border to h1 and h2 */
  border-bottom: solid 1px #666;
}
h2 { /* Resize header 2: */
  font-size: 22px;
}
body { /* Make main text colour black */
  color: black;
}
a { /* Link colours */
  color: blue;
}
.tocify { /* Some toc fixes*/
  width: 100% !important;
  border: none; /* remove border */
}
.tocify-header { /* fix for horrible indent in toc */
  text-indent: initial;
}

```


```{r, eval=FALSE}
library("tidyverse")
library("devtools")
library("glue")
library("dplyr")
library("stringr")
library("ggplot2")
library("knitr")
library("ggrepel")
library("patchwork")
library("janitor")
library("usethis")
library("roxygen2")
library("testthat")

```

init some libraries

```{r, eval=TRUE}

light = read.table("light.dat", header = TRUE)
farm = read.table("farm.dat", header = TRUE)
fertile = read.table("fertile.dat", header = TRUE)
```
Read the data

```{r, eval=TRUE}

# Population paramter is the difference of meanso

# when we minus u 1 - u 2, our h0 is if the two numbers == 0. Since its not == to 0, then we are 95% sure that we can reject the null hypothesis. 

lSDOne <- sd(light$Brand1)
lSDTwo <- sd(light$Brand2)

out = t.test(light$Brand1, light$Brand2, var.equal = TRUE)
names(out)

pValue = t.test(light$Brand1, light$Brand2, var.equal = TRUE)$p.value
pValue

```

Find SD of both lights and do t test

```{r}


# q1----------------------------------------------------

# equal variace assumption is done here since its close.

# As the means are the same, we can reject the null hypothesis 

# Show data summary

pValue = t.test(light$Brand1, light$Brand2, var.equal = TRUE)$p.value

# Show which tails im doing
if(pValue < 0.05) {
  print("Reject")
} else {
  print("Do Not Reject")
}
par(mfrow=c(1,2))
boxplot(light$Brand1, data = light)
boxplot(light$Brand2, data = light)
boxplot(light)



summary(light$Brand1)
summary(light$Brand2)
mean(light$Brand1)
mean(light$Brand2)
sd(light$Brand1)
sd(light$Brand2)
stem(light$Brand1)
stem(light$Brand2)
bob <- qqnorm(light$Brand1)
bob

#'
#'ggplot(data = light, mapping = aes(x = light$Brand1, y = light$Brand2))
```

```{r}
# Need of 2 sample t test on this set of data
attach(farm)

t.test(farm$yield ~ farm$plot, paired = TRUE)
# boxplot(farm$plot ~ farm$yield, data = farm, horizontal = TRUE)
summary(farm$yield)
summary(farm$plot)
mean(farm$yield)
sd(farm$yield)
stem(farm)

yield <- data.frame(sprayed=farm$yield[farm$plot == "sprayed"], unsprayed=farm$yield[farm$plot == "unsprayed"])
yield$difference <- yield$sprayed - yield$unsprayed
yield
yield$sprayed 


t.test(yield$sprayed ~ yield$unsprayed, paired = TRUE)

```

```{r}

# q3 ----------------------------------------------------
t.test(fertile$nonfertile, fertile$fertile, paired = TRUE)
summary(fertile$fertile)
summary(fertile$fertile)
mean(fertile$fertile)
sd(fertile$fertile)
stem(fertile$fertile)
summary(fertile$nonfertile)
mean(fertile$nonfertile)
sd(fertile$nonfertile)
stem(fertile$nonfertile)

boxplot(fertile ~ nonfertile, data = fertile, horizontal = TRUE)

```








